action_id: trunk-cache-prune
date: 2023-12-09 07:14:14
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1702106054
full_timestamp:
  nanos: 267348000
  seconds: 1702106054
trunk_version: 1.18.0
